#!/bin/bash

set -eu
set -o pipefail

rsync -vutzr --chmod u=rwx,go=rx --force --progress --partial \
	--exclude='.git' \
	--exclude='.DS_Store' \
	--exclude='deploy-website' \
	*  relcy-p0:/var/www/relcy.com/
 